pagopa/io-sign

apps/io-func-sign-issuer/Info/function.json
apps/io-func-sign-issuer/src/infra/__mocks__/signer.ts
apps/io-func-sign-issuer/src/infra/azure/functions/create-signature-request.ts
apps/io-func-sign-issuer/src/infra/azure/functions/info.ts

feat(io-func-sign-issuer): Add Info endpoint [SFEQS-1155]

---

apps/io-func-sign-issuer/src/infra/__mocks__/signer.ts
apps/io-func-sign-issuer/src/infra/azure/functions/create-dossier.ts
apps/io-func-sign-issuer/src/infra/azure/functions/create-signature-request.ts
apps/io-func-sign-issuer/src/infra/azure/functions/get-dossier.ts
apps/io-func-sign-issuer/src/infra/azure/functions/get-upload-url.ts
apps/io-func-sign-issuer/src/infra/azure/functions/info.ts
apps/io-func-sign-issuer/src/infra/azure/functions/set-signature-request-status.ts
apps/io-func-sign-issuer/src/infra/azure/functions/validate-upload.ts
packages/io-sign/src/document.ts
packages/io-sign/src/infra/http/__test__/errors.spec.ts
packages/io-sign/src/infra/http/__test__/response.spec.ts
packages/io-sign/src/infra/http/response.ts
packages/pdv-tokenizer/.eslintrc.json

this PR performs a lint fix on the entire basecode!

fix: Lint fix [SFEQS-1161]

---

apps/io-func-sign-issuer/src/app/use-cases/get-upload-url.ts

1. Add a "guard" in the `getUploadUrl` use case that checks the status of the `Signature Request`
The Issuer should not upload new files after the SR is marked as `READY`

Fix: prevent generation of Upload URL (Sas Token) when the SR is not DRAFT [SFEQS-1124]

---

apps/io-func-sign-user/openapi.yaml

This PR modifies the user-side openapi specifications to make them compatible with the io-backend generator

chore(user): [SFEQS-1183] Change openapi 

---

apps/io-func-sign-issuer/src/infra/azure/storage/upload.ts

This PR fix a bug that doesn't generate sas tokens correctly

bug(issuer): [SFEQS-1188] SAS token options

---

apps/io-func-sign-user/openapi.yaml

chore(user): [SFEQS-1138] Minor fix openapi

---

.github/workflows/publish-package.yaml
README.md
apps/io-func-sign-user/package.json

1. Remove unused files
2. Make `io-func-sign-user` deployable
3. Change copy on NPM publish workflow
4. Add "code review" badge on `README.md`

chore: [SFEQS-1143] Minor changes

---

.changeset/two-crews-change.md
apps/io-func-sign-user/openapi.yaml
apps/io-func-sign-user/src/infra/azure/functions/create-filled-document.ts

This PR add `Location` header to `/qtsp/clauses/filled_document` endpoint response.

chore:(user): Add location to 201 response header [SFEQS-1217]

---

.changeset/selfish-colts-fail.md
apps/io-func-sign-user/openapi.yaml

Refactor openapi for `QtspClausesMetadataDetailView`

Chore(user): Refactor openapi [SFEQS-1218]

---

apps/io-func-sign-issuer/Info/function.json
apps/io-func-sign-user/Info/function.json

Changed info endpoints access level.
Health check endpoints must be publicly accessible.

fix: [SFEQS-1227] Fix anonymous access to info endpoints

---

.changeset/red-tables-complain.md
apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts
apps/io-func-sign-issuer/src/infra/azure/functions/send-notification.ts

This PR aligns the signature message with what is intended by design

chore(issuer): [SFEQS-1224] Align notification message

---

apps/io-func-sign-user/src/app/use-cases/__mocks__/qtsp.ts
apps/io-func-sign-user/src/signature-field.ts

This pr fix a bug on signature with coordinates!

fix(user): [SFEQS-1210] Fix Signature coordinates

---

apps/io-func-sign-user/src/app/use-cases/__mocks__/qtsp.ts
apps/io-func-sign-user/src/app/use-cases/create-signature.ts

Add mock for fiscal code accepted by QTSP

chore(user): Mock fiscal code [SFEQS-1241]

---

.changeset/slimy-parents-know.md
apps/io-func-sign-issuer/src/signature-request.ts
apps/io-func-sign-user/src/app/use-cases/create-signature.ts
apps/io-func-sign-user/src/infra/azure/functions/create-signature.ts
apps/io-func-sign-user/src/infra/http/encoders/signature-request.ts
apps/io-func-sign-user/src/signature-request.ts
packages/io-sign/src/document.ts
packages/io-sign/src/signature-request.ts

This PR add the `WAIT_FOR_QTSP` status to Signature Request.

chore: [SFEQS-1250] Add WAIT_FOR_QTSP status to signature request

---

.changeset/thirty-wolves-turn.md
apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts
apps/io-func-sign-user/src/app/use-cases/__mocks__/notification.ts

This PR aligns the notification messages with what is intended by the design on Figma!

chore: [SFEQS-1276] Aligned notification messages with Figma

---

.changeset/tame-clouds-repeat.md
apps/io-func-sign-issuer/src/app/use-cases/mark-request-rejected.ts
apps/io-func-sign-issuer/src/app/use-cases/mark-request-signed.ts
apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts

This PR aligns the text of the messages sent with what is foreseen by the design on figma!

chore: Update notification text message [SFEQS-1371, SFEQS-1367]

---

.changeset/lazy-garlics-wave.md
apps/io-func-sign-issuer/openapi.yaml
apps/io-func-sign-issuer/src/infra/http/decoders/document.ts

1. Changed OpenAPI spec in order to make `signature_fields` field optional
this change it was e2e tested manually

fix(issuer): [SFEQS-1363] Make "signature_fields" field optional in REST APIs

---

.changeset/mean-queens-warn.md
apps/io-func-sign-issuer/src/__test__/signature-request-notification.spec.ts
apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts
apps/io-func-sign-issuer/src/__test__/upload.spec.ts
apps/io-func-sign-issuer/src/infra/http/decoders/document.ts
apps/io-func-sign-user/src/__test__/third-party-message.spec.ts
packages/io-sign/src/__test__/document.spec.ts
packages/io-sign/src/document.ts

1. Created a new codec for `SignatureFields` that checks the "require at least one mandatory signature" constraint
The change has been unit tested

feat(issuer): [SFEQS-1351] Require at least one mandatory signature

---

.changeset/tame-oranges-share.md
apps/io-func-sign-issuer/src/__test__/signature-request-notification.spec.ts
apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts
apps/io-func-sign-issuer/src/__test__/upload.spec.ts
apps/io-func-sign-issuer/src/dossier.ts
apps/io-func-sign-issuer/src/signature-request.ts
apps/io-func-sign-user/openapi.yaml
apps/io-func-sign-user/src/__test__/signature-request.spec.ts
apps/io-func-sign-user/src/__test__/third-party-message.spec.ts
apps/io-func-sign-user/src/infra/azure/cosmos/signature-request.ts
apps/io-func-sign-user/src/infra/http/encoders/signature-request.ts
packages/io-sign/src/__test__/event.spec.ts
packages/io-sign/src/signature-request.ts

1. Add `dossierTitle` property on `SignatureRequest` entity
It was e2e tested manually

feat(user): [SFEQS-1475] Add dossier title to Signature Request

---

apps/io-func-sign-support/openapi.yaml

1. Add `securityScheme` in `openapi.yaml`
This service will be consumed via APIM that requires this header

docs(support): Add security scheme in OpenAPI spec

---

.changeset/friendly-rivers-return.md
apps/io-func-sign-issuer/host.json
apps/io-func-sign-issuer/local.settings.json.example
apps/io-func-sign-user/host.json
apps/io-func-sign-user/local.settings.json.example

Adds support to the `console.log ` in the `host.json` file
The use of console.log is different from the context.log therefore logging via console must also be enabled.

chore: [SFEQS-1596] Add console log support to host.json

---

.changeset/config.json
.github/labeler.yml
.github/workflows/azure-deploy.yaml
.github/workflows/release.yaml
package.json

- configured `changesets` tools to handle private packages
- release function can build and create github releases with artifacts
- added github action to deploy on azure via self-hosted runners
Automate the build and the release processes

ci: [SFEQS-949] Migrazione pipeline di deploy a GitHub actions

---

.identity/03_github_environment_cd.tf
.identity/03_github_environment_runner.tf
.identity/99_locals.tf
.identity/env/prod/terraform.tfvars

- fix prefix on runner environment
- fix environment protection rune

fix(ci): [SFEQS-1279] identity environment fix

---

.opex/api_issuer/env/prod/config.yaml

- tuning response time threshold relative to issuer API

fix(opex): Tuning response time threshold

---

.changeset/grumpy-apes-compete.md
.vscode/extensions.json
.vscode/settings.json
apps/io-func-sign-issuer/GetRequestsByDossier/function.json
apps/io-func-sign-issuer/io-func-sign-issuer.rest
apps/io-func-sign-issuer/openapi.yaml
apps/io-func-sign-issuer/src/app/main.ts
apps/io-func-sign-issuer/src/infra/azure/cosmos/signature-request.ts
apps/io-func-sign-issuer/src/infra/azure/functions/get-requests-by-dossier.ts
apps/io-func-sign-issuer/src/infra/http/encoders/signature-request.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-requests-by-dossier.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/get-requests-by-dossier.ts
apps/io-func-sign-issuer/src/signature-request.ts

1. Add `GetRequestsByDossier` function
2. Add support for vscode `rest-client` in order to easily test the rest API
Without this endpoint issuers would have no way of seeing the list of sent signature requests

feat(issuer): [SFEQS-1370] Add endpoint to get Signature Requests by Dossier

---

.changeset/friendly-maps-provide.md
packages/io-sign/src/event.ts

Add the `signerId` parameters to billing and analytics events.

chore: [SFEQS-1633] Add `signerId` to billing and analytics events

---

.changeset/chilled-sheep-float.md
apps/io-func-sign-issuer/openapi.yaml
apps/io-func-sign-issuer/src/infra/http/encoders/signature-request.ts

1. Add `getRequestsByDossier` operation in `OpenAPI` spec (thanks to @filippo-tenaglia )
2. Fix casing (from camel case to snake case) of `continuation_token` property
This newly added endpoint was missing from OpenAPI (maybe due to an error on Git merge..)
This endpoint is unit tested and they still pass after the edit

fix: [SFEQS-1647] Add getRequestsByDossier in OpenAPI

---

apps/io-func-sign-issuer/package.json
apps/io-func-sign-support/package.json
apps/io-func-sign-user/local.settings.json.example
apps/io-func-sign-user/package.json
yarn.lock

Add missing properties in `local.settings.json.example` in workspace `io-func-sign-user`

chore: Add missing properties in local.settings.json.example

---

apps/io-func-sign-issuer/src/signature-request.ts
apps/io-func-sign-user/local.settings.json.example
apps/io-func-sign-user/src/app/config.ts
apps/io-func-sign-user/src/app/main.ts
apps/io-func-sign-user/src/app/use-cases/create-signature-request.ts
apps/io-func-sign-user/src/infra/azure/functions/create-signature-request.ts
packages/io-sign/src/infra/io-link/config.ts
packages/io-sign/src/infra/io-link/qr-code.ts
packages/io-sign/src/signature-request.ts

Update the `signatureRequest` qr-code url according to `io-link`.
- Add `io-link` integration
- Update qr-code parameter of `signatureRequest` dynamically calculated
It still uses the old make methods and not RTE as the `io-sign` package hasn't been migrated yet

chore: [SFEQS-1641] Update qr-code url according to io-link 

---

apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
apps/io-func-sign-issuer/src/infra/http/handlers/create-signature-request.ts
packages/io-sign/src/event.ts
packages/io-sign/src/infra/azure/event-hubs/event.ts

Swapped parameters in `createAndSendAnalyticsEvent` function in workspace `io-func-sign-issuer`

fix(issuer): createAndSendAnalyticsEvent

---

packages/web-sdk/package.json
packages/web-sdk/vite.config.ts
yarn.lock

1. Add rollup plugin to `vite` config to minify the output bundle

build(web-sdk): [SFEQS-1645] Minify io-sign sdk library code

---

.github/workflows/azure-deploy.yaml

- Update the `AzureDeploy` Github Action to correctly deploy
Fix a bug that did not allow to correctly deploy to Azure

[SFEQS-1655]: Update deploy to Azure

---

.changeset/tame-hornets-bow.md
packages/web-sdk/index.html
packages/web-sdk/src/components/Button.ts
packages/web-sdk/src/io-sign.ts

1. refactored the `disabled` property to act as a boolean
the previous implementation made the CTA clickable even when disabled

fix(web-sdk): [SFEQS-1697]  Fix incorrect behaviour on "disabled" state

---

.opex/api_issuer/env/prod/config.yaml
.opex/api_support/env/prod/config.yaml
.opex/api_user/env/prod/config.yaml

- Added additional action groups to opex configuration
Allow the "Sign" team to quickly identify the relevant alarms
Separation of duties on alarm reaction

feat(opex): [SFEQS-1627] Allarmi OpEx dashboard su channel Slack dedicato

---

.opex/api_issuer/env/prod/config.yaml
.opex/api_support/env/prod/config.yaml
.opex/api_user/env/prod/config.yaml

- overriding value for response time threshold 
Avoid false positive alarms

fix(user): opex tuning alarm signatures response time

---

apps/io-func-sign-issuer/openapi.yaml
apps/io-func-sign-support/openapi.yaml
apps/io-func-sign-support/src/infra/http/encoders/signature-request.ts
apps/io-func-sign-support/src/signature-request.ts

1. Added `CANCELLED` to the signature request status in `io-func-sign-support` workspace
2. Added `cancelled_at` to signature request in `openapi.yaml` in `io-func-sign-issuer` workspace

chore: [SFEQS-1848] Add CANCELLED status to io-func-sign-support workspace

---

docs/architecture/decisions/0006-use-vitest-as-unit-test-framework.md
docs/architecture/decisions/0007-use-turborepo-as-task-manager.md
docs/architecture/decisions/README.md

Date: 2023-06-26
Accepted
Since we are working on a multi-project codebase we need a tool that helps us running tasks (such as build, test) across the projects.
`yarn` and `npm` in `workspace` mode,
Since we are working on a multi-project codebase, we need a tool that allows us to execute tasks (such as build, code review or test) across projects.
We need a tool that:
- is easy to install and maintain, and compatible to `yarn workspaces`
- allows us to execute tasks across the projects
- can executes task in parallel
- can cache the results of task execution
- works on CI
The package manager we use (`yarn`) supports a subset of such use-cases, so we need to choose between two different (external) tools.
`nx` is the de-facto standard for managing multi-project codebases in JavaScript. It …

docs: ADR on choosing the right task manager for our codebase

---

.github/workflows/opex-review/action.yaml
.github/workflows/opex_api_issuer_review.yaml
.github/workflows/opex_api_support_review.yaml
.github/workflows/opex_api_user_review.yaml

Defining github actions to check opex config file and openapi syntax
When modifying the swagger file, we want to be sure it will be valid against the specification

ci: [SFEQS-1603] add GitHub action to validate openapi spec (using the OPEX validator)

---

.changeset/blue-socks-mate.md
apps/io-func-sign-issuer/host.json
apps/io-func-sign-support/host.json
apps/io-func-sign-user/host.json

Configure `host.json` file to allow application insight and monitor logging
Default logging set to `None` prevented execution metrics and traces to be delivered to Application Insight and Monitor tool
Please notice the "Caution" box at the end of the ["Configure log levels"](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels) paragraph.

fix: [SFEQS-1772] Configure host logging properties to allow monitoring execution

---

docs/architecture/decisions/0008-project-structure.md

Date: 2023-06-30
Accepted
`io-sign` is a system composed of several microservices, libraries, and frontends. These components are JavaScript projects built with TypeScript on Node.js. Therefore, from a technological standpoint, they are homogeneous.
This document aims to explain the structure of the codebase that we have adopted.
We have made the decision to manage the entire codebase using a JavaScript monorepo, utilizing `yarn workspaces`. Below is a description of the folder structure of the project:
- `docs/`
- `apps/` - standalone applications, that will be deployed on cloud services (such as microservices or static web sites)
- `packages/` - modules meant to be included in other `packages` or `apps`
- `package.json`
In the case of workspaces that do not utilize opinionated …

docs(adr): [SFEQS-1308] Document project structure

---

apps/io-sign-backoffice-app/src/app/api/api-keys/_lib/__test__/api-key.spec.ts
apps/io-sign-backoffice-app/src/app/api/institutions/[institutionId]/api-keys/[apiKeyId]/route.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/__test__/api-key.spec.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/__test__/fiscal-code.spec.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/__test__/ip-address.spec.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/api-key.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/fiscal-code.ts
apps/io-sign-backoffice-app/src/app/api/institutions/_lib/ip-address.ts

1. Added `POST` function in `/src/app/api/institutions/{institutionId}/api-keys/{apiKeyId}`
2. Added `listFiscalCodes` and `listIpAddresses` functions
3. Added unit tests
Through unit tests

feat(backoffice): [SFEQS-1764] Added ip addresses and fiscal codes functions

---

apps/io-sign-backoffice-app/src/app/api/api-keys/_lib/api-key.ts

chore(backoffice): Removed environment filter in api keys list

---

apps/io-sign-backoffice-app/.env
apps/io-sign-backoffice-app/package.json
apps/io-sign-backoffice-app/src/app/api/api-keys/_lib/__test__/api-key.spec.ts
apps/io-sign-backoffice-app/src/app/api/api-keys/_lib/api-key.ts
apps/io-sign-backoffice-app/src/lib/apim.ts
yarn.lock

The `@azure/arm-apimanagement` and `@azure/identity` dependencies have been removed. Now the API management REST API with access token is used.
Through unit tests

chore(backoffice): Replace arm SDK with API Management REST API

---

apps/io-sign-backoffice-app/package.json
apps/io-sign-backoffice-app/src/app/health/route.ts
apps/io-sign-backoffice-app/src/lib/apim.ts
yarn.lock

1. Replace API Management REST API with `@azure/arm-apimanagement` SDK
2. Enable APIM in healthcheck
`@azure/arm-apimanagement` allows us to integrate with APIM using `managed identitites` instead of relying on secrets and connection strings.

refactor(bo): [SFEQS-1991] Replace API Management REST API with @azure/arm-apimanagement SDK

---

.github/workflows/code-review.yaml
.github/workflows/publish-package.yaml
apps/io-func-sign-issuer/package.json
apps/io-func-sign-issuer/tsconfig.json
apps/io-func-sign-issuer/tsup.config.js
apps/io-func-sign-support/package.json
apps/io-func-sign-support/tsconfig.json
apps/io-func-sign-support/tsup.config.js
apps/io-func-sign-user/package.json
apps/io-func-sign-user/tsconfig.json
apps/io-func-sign-user/tsup.config.js
apps/io-sign-backoffice-app/package.json
apps/io-sign-backoffice-app/tsconfig.json
package.json
packages/io-sign-issuer-sdk/package.json
packages/io-sign-issuer-sdk/tsconfig.json
packages/io-sign/package.json
packages/io-sign/tsconfig.json
packages/web-sdk/package.json
yarn.lock

1. Updated some dev dependencies
2. Updated some configuration with node `18`

chore: [SFEQS-1381] Update config with node 18

---

apps/io-func-sign-issuer/src/__test__/signature-request-notification.spec.ts
apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts
apps/io-func-sign-issuer/src/__test__/upload.spec.ts
apps/io-func-sign-issuer/src/infra/back-office/issuer.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/create-dossier.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/create-signature-request.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-dossier.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-requests-by-dossier.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-signature-request.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/set-signature-request-status.spec.ts
apps/io-func-sign-issuer/src/infra/http/handlers/__test__/validate-document.spec.ts
apps/io-func-sign-issuer/src/infra/self-care/encoder.ts
apps/io-func-sign-issuer/src/issuer.ts
apps/io-sign-backoffice-app/src/lib/__test__/issuers.spec.ts
apps/io-sign-backoffice-app/src/lib/issuers/index.ts
apps/io-sign-backoffice-app/src/lib/issuers/use-cases.ts
packages/io-sign/src/__test__/event.spec.ts
packages/io-sign/src/infra/azure/__test__/event-hubs.spec.ts
packages/io-sign/src/issuer.ts

Add issuer `state` property when issuer is created in `io-sign-backoffice-app` and `io-func-sign-issuer`
An issuer could withdraw from the contract and we have to handle this case.  So we need a issuer property `state` with values `active` and `inactive`.

chore: [SFEQS-2024] Add state property to issuer

---

apps/io-sign-backoffice-func/local.settings.json.example

chore: Add local.settings.json.example file in io-sign-backoffice-func

---

apps/io-sign-backoffice-func/src/functions/health.ts
apps/io-sign-backoffice-func/src/functions/on-selfcare-contracts-message.ts
apps/io-sign-backoffice-func/src/main.ts

Add health check function for `io-sign-backoffice-func` function app

feat(bo): Add health check function

---

apps/io-sign-backoffice-app/next.config.js
apps/io-sign-backoffice-app/package.json
package.json
yarn.lock

1. remove `sharp` (and `adr`, that is unused and has `sharp` as dependency)
2. disable image optimization on `io-sign-backoffice-app`
There are some memory leaks in production, we are investigating to understand the causes. One source could be `sharp`, used by Next.js to optimize images.

chore(bo): disable image optimization

---

.changeset/fifty-ravens-bake.md
apps/io-sign-backoffice-app/.env
apps/io-sign-backoffice-app/.env.development
apps/io-sign-backoffice-app/src/lib/__test__/api-keys.spec.ts
apps/io-sign-backoffice-app/src/lib/__test__/issuers.spec.ts
apps/io-sign-backoffice-app/src/lib/api-keys/use-cases.ts
apps/io-sign-backoffice-app/src/lib/auth/use-cases.ts
apps/io-sign-backoffice-app/src/lib/issuers/index.ts
apps/io-sign-backoffice-app/src/lib/issuers/use-cases.ts
apps/io-sign-backoffice-app/src/lib/slack.ts

1. Added `sendMessage` that sends slack messages
2. Used `sendMessage` to notify first access to portal and api key creation
Our product team needs to be notified promptly about certain backoffice events

chore(bo): [SFEQS-2008] Send slack notification

---

.github/workflows/deploy-issuer-func.yaml
.github/workflows/deploy-support-func.yaml
.github/workflows/deploy-user-func.yaml

Add deploy pipelines for `issuer`, `user` and `support` service
These pipelines replaces the old `azure-deploy` pipeline

ci: [SFEQS-1823] Add deploy pipelines

---

.changeset/nice-islands-impress.md
apps/io-sign-backoffice-app/package.json
yarn.lock

1. Update `zod`
The previous version of this library does not correctly validate some types of email addresses. See https://github.com/colinhacks/zod/issues/2396

fix(bo): [SFEQS-2050] Update Zod to its latest version

---

.github/workflows/opex_api_issuer.yaml

Add quotes to parameter
For some reason, the parameter value is not read properly by the action. So this is a try to see if anything get solved. Also added `workflow_dispatch` to avoid any other "test PR" while trying to fix this..

fix: Add quotes to GH Action input parameter

---

.github/workflows/opex_api_issuer.yaml
.github/workflows/opex_api_support.yaml
.github/workflows/opex_api_user.yaml
.identity/env/prod/terraform.tfvars

Reintroduce matrix
Give right IAM roles to identity
For some WEIRD reason, the `environment` value is not read by the child action if a `matrix` is not defined.
No matrix
With matrix

[EC-65] Fix Opex CD pipelines

---

apps/io-func-sign-user/local.settings.json.example

fix(user): Added IoServicesConfigurationId env variable to example file

---

.changeset/wet-dingos-suffer.md
apps/io-func-sign-issuer/src/app/use-cases/__test__/close-signature-request.spec.ts
apps/io-func-sign-issuer/src/app/use-cases/close-signature-request.ts

chore(issuer): [SFEQS-2145] Added environment to io.sign.signature_request.rejected event context

---

.github/workflows/deploy-issuer-func.yaml

Added a step that deletes the `latest` tag. Also added the `continue-on-error` property, which ensures that the workflow will continue to execute the following step if the tag does not exist
The `deploy-issuer-func` workflow always fails because it tries to create the `latest` tag which already exists

fix(issuer): [SFEQS-2146] Updated deploy issuer GitHub workflow

---

.changeset/silver-horses-cross.md
apps/io-sign-backoffice-app/src/components/AccountHeader.tsx

It was asked to each product stream by the Selfcare team

chore(bo): [SFEQS-2126] Updated assistenza url redirect

---

.changeset/gentle-chairs-wink.md
apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-details.ts

Removed the check if the signature request has been signed more than 90 days ago in `GetThirdPartyMessageDetails`
Firma con IO must always return the metadata of the attachments even after their expiration so that their retrieval results in a 404 error, enabling proper error handling in the app
https://pagopa.atlassian.net/wiki/spaces/IC1/pages/862978217/Cross-domain+impacts

fix(user): [SFEQS-2144] Updated GetThirdPartyMessageDetails

---

.changeset/silly-melons-melt.md
apps/io-sign-backoffice-app/src/app/[locale]/[institution]/_components/SupportCard.tsx
apps/io-sign-backoffice-app/src/i18n/messages/it.json
apps/io-sign-backoffice-app/src/lib/support.ts

In the back office `Assistenza Tecnica`, in the production phase, I replaced the email with the reference to `Assistenza` CTA

chore(bo): [SFEQS-2147] Updated Assistenza tecnica in Panoramica

---

apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
packages/io-sign/src/institution.ts

`vatNumber` in `billing` in `sc-contracts` queue could be null

fix: vatNumber could be null

---

.changeset/nice-pears-rest.md

fix: run changeset

---

.changeset/quiet-meals-buy.md
apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
packages/io-sign/src/institution.ts

fix: set optional vatnumber

---

.changeset/warm-waves-peel.md
apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
packages/io-sign/src/institution.ts

fix: set vatNumber as nullish

---

.changeset/shiny-rules-tell.md
apps/io-sign-backoffice-func/src/infra/google/config.ts

fix: added base64 decode to GOOGLE_PRIVATE_KEY

---

publiccode.yml

This PR:
* adds a `publiccode.yml` metadata file to the repository. 
Our internal policy requires to have a `publiccode.yml` file for each public FOSS repo.

Add publiccode.yml metadata file

---

.changeset/silent-files-try.md
apps/io-func-sign-user/src/infra/azure/functions/create-signature.ts

updated minutes download file validity to 30

---

.changeset/little-laws-refuse.md
apps/io-func-sign-user/package.json

fix: updated user package.json

---

.changeset/rare-pumas-repair.md
apps/io-func-sign-user/src/infra/azure/functions/create-signature.ts

scale SAAS token URL to 60 minutes
