apps/io-func-sign-issuer/openapi.yaml, apps/io-func-sign-issuer/src/infra/http/decoders/signature-request.ts, apps/io-func-sign-issuer/src/infra/http/encoders/signature-request.ts, apps/io-func-sign-issuer/src/signature-request.ts, apps/io-func-sign-issuer/src/upload.ts, packages/io-sign/src/document.ts
This PR add `REJECTED` status to Signature Request with `rejected_reason` and `uploaded_at` fields.
=> refactor: Add REJECTED status to Signature Request [SFEQS-1147]

apps/io-func-sign-issuer/openapi.yaml, apps/io-func-sign-issuer/src/infra/azure/functions/get-signer.ts, apps/io-func-sign-issuer/src/infra/azure/functions/send-notification.ts, packages/io-services/src/profile.ts
This PR adds control over the user profile before returning a signerId. In this way, unauthorized users will be excluded.
E2E manually tested
=> core: integrate getProfile with tokenizer in getSigner

.github/pull_request_template.md, .github/release.yaml, .github/workflows/conventional-labels.yaml, TODO
Added GitHub workflow to automatically apply conventional labels on Pull Request.
This change let group Pull Requests by intent and generate nice GitHub release notes.
=> chore: [SFEQS-1172] Add GitHub action to apply conventional labels

.changeset/honest-radios-cover.md, apps/io-func-sign-issuer/openapi.yaml, apps/io-func-sign-issuer/src/infra/http/encoders/document.ts
1. Changed the `openapi spec` in order to discriminate the document statuses
Due to the incorrect structure of the OpenAPI specification, some fields of Document were excluded from the responses.
It was tested manually
=> fix: [SFEQS-1141] GetSignatureRequest now serializes the correct Document attributes

.changeset/three-forks-shout.md, apps/io-func-sign-user/src/signature-field.ts
1. Round coordinates in `io-func-sign-user`, now are all integers
The QTSP accepts only integer coordinates
=> fix: [SFEQS-1238] Round coordinates for QTSP 

.changeset/five-hornets-sort.md, apps/io-func-sign-user/src/app/use-cases/__mocks__/qtsp.ts, apps/io-func-sign-user/src/app/use-cases/create-signature.ts, packages/io-sign/src/infra/pdf.ts
This PR creates a custom Spid Assertion Mock with user data contained in the pdf signature request form.
⚠️ Before deployment requires a change to the `SpidAssertionMock` environment variable
With this change, the name of the signer on signed PDF will no longer be the same but varies according to the signer.
=> chore: [SFEQS-1269] Create a custom SAML mock

.changeset/popular-papayas-buy.md, apps/io-func-sign-user/package.json, apps/io-func-sign-user/src/app/use-cases/create-signature.ts, apps/io-func-sign-user/src/infra/namirial/client.ts, apps/io-func-sign-user/src/signature-request.ts, packages/io-sign/src/signature-request.ts
This PR adds support to the `REJECTED` state of the signature request giving the possibility to recreate a signature even when the state is rejected.
It also adds a preliminary status check before proceeding with signature creation. This allows to avoid calling the _QTSP_ if it is not possible to proceed with the signature.
Also moved the local port for `io-func-sign-user` from `7071` to `7072` so that both instances (issuer and user) can be running.
Tested locally
=> chore: [SFEQS-1277] Add support for REJECTED status for signature request.

.changeset/lovely-days-admire.md, apps/io-func-sign-issuer/openapi.yaml, apps/io-func-sign-issuer/src/infra/http/encoders/signature-request.ts, apps/io-func-sign-issuer/src/signature-request.ts, packages/io-sign/src/infra/http/__test__/errors.spec.ts, packages/io-sign/src/infra/http/errors.ts
1. `rejected_at` is now returned when a `SignatureRequest` is `REJECTED`
2. `CreateDossier` returns `400 (Bad Request)` instead of `500 (Internal Server Error)` when validation fails on `documents_metadata`
3. `CreateSignatureRequest` returns `400 (Bad Request)` instead of `500 (Internal Server Error)` when validations fails on `expires_at`
=> fix: [SFEQS-1182, SFEQS-1244, SFEQS-1221] Fix rest API responses

.changeset/rare-cows-fail.md, apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts, apps/io-func-sign-issuer/src/__test__/upload.spec.ts, apps/io-func-sign-issuer/src/app/use-cases/create-signature-request.ts, apps/io-func-sign-issuer/src/signature-request.ts, apps/io-func-sign-user/openapi.yaml, apps/io-func-sign-user/src/__test__/signature-request.spec.ts, apps/io-func-sign-user/src/infra/http/encoders/signature-request.ts, packages/io-sign/src/issuer.ts, packages/io-sign/src/signature-request.ts
1. Add `issuerDescription` and `issuerEmail` field in `SignatureRequest`
2. Extend `io-func-sign-user`'s OpenAPI spec to include `issuer` property with `e-mail` and `description`
This issuer data is requested in the mobile screens. At the moment they are persisted in the Signature Request as we are not yet integrated into Selfcare.
=> feat: [SFEQS-1259] Extend Signature Request to include Issuer e-mail and description

.changeset/wet-boats-wash.md, apps/io-func-sign-issuer/MarkAsRejected/function.json, apps/io-func-sign-issuer/MarkAsSigned/function.json, apps/io-func-sign-issuer/src/app/main.ts, apps/io-func-sign-issuer/src/app/use-cases/mark-request-rejected.ts, apps/io-func-sign-issuer/src/app/use-cases/mark-request-signed.ts, apps/io-func-sign-issuer/src/infra/azure/functions/mark-as-rejected.ts, apps/io-func-sign-issuer/src/infra/azure/functions/mark-as-signed.ts, apps/io-func-sign-issuer/src/signature-request.ts, apps/io-func-sign-user/src/app/main.ts, apps/io-func-sign-user/src/app/use-cases/validate-signature.ts, apps/io-func-sign-user/src/infra/azure/functions/create-signature-request.ts, apps/io-func-sign-user/src/infra/azure/functions/validate-signature.ts, apps/io-func-sign-user/src/infra/azure/storage/signature-request.ts, apps/io-func-sign-user/src/signature-request.ts
1. Add two functions on the issuer side `MarkAsSigned` and `MarkAsRejected`
2. Add event emitters (backed by Azure Storage Queue)
since the signature request is stored in two separate databases, we have to keep them in sync
=> [SFEQS-1222] Keep Signature Request statuses consistent across the system

.changeset/tame-pandas-applaud.md, apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts, apps/io-func-sign-issuer/src/__test__/upload.spec.ts, packages/io-sign/src/issuer.ts
This PR add isTrying field to issuer data and remove unused fields.
The need is to know if an issuer is in the experimental phase or not. We will use this field to communicate to data-lake whether the signing event should be billed or not and at the same time to route the request to the QTSP towards a demo or production environment. The addition has been made now to avoid breaking changes during the initial experimentation.
=> chore!: [SFEQS-1333] Add the ability to mark an issuer as a no-billable test account

.changeset/silly-drinks-turn.md, apps/io-func-sign-issuer/src/app/main.ts, apps/io-func-sign-issuer/src/infra/azure/functions/get-signature-request.ts, apps/io-func-sign-user/src/app/use-cases/create-signature.ts, apps/io-func-sign-user/src/infra/azure/functions/create-signature.ts, apps/io-func-sign-user/src/infra/azure/functions/get-signature-request.ts, packages/io-sign/src/document-url.ts, packages/io-sign/src/infra/azure/storage/document-url.ts
⚠️ ACHTHUNG!  I'm working on a broader change to track url permissions in the domain, it will come with one of the next PRs
1. Generate SAS urls on `GetSignatureRequest` endpoint on the issuer side
2. Move common code to `@io-sign/io-sign`
the issuer should be able to download the signed documents from the "GetSignatureRequest" endpoint; until now the files could not be downloaded
=> fix(issuer): [SFEQS-1348] Pre-authenticate urls on SIGNED requests

.changeset/ten-hornets-dream.md, apps/io-func-sign-issuer/host.json, apps/io-func-sign-user/host.json
This PR sets the `maxPollingInterval` for queues to 5 seconds and try to solve the problem of waiting more than one minute for the signature request status to change from `READY` to `WAIT_FOR_SIGNATURE`.
The [queuetrigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger) implements a random exponential back-off algorithm. As a result of this if there are no messages on the queue, the SDK will back off and start polling less frequently.
`MaxPollingInterval` allows us to configure this behavior. It for when a queue remains empty, the longest period of time to wait before checking for a message to.
=> chore: [SFEQS-1350] Add maxPollingInterval for queues

.changeset/three-tips-occur.md, .changeset/tidy-colts-fetch.md, apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts, apps/io-func-sign-issuer/src/signature-request.ts, apps/io-func-sign-issuer/src/upload.ts, apps/io-func-sign-user/GetThirdPartyMessageAttachmentContent/function.json, apps/io-func-sign-user/GetThirdPartyMessageDetails/function.json, apps/io-func-sign-user/openapi.yaml, apps/io-func-sign-user/package.json, apps/io-func-sign-user/src/__test__/signature-request.spec.ts, apps/io-func-sign-user/src/__test__/third-party-message.spec.ts, apps/io-func-sign-user/src/app/main.ts, apps/io-func-sign-user/src/app/use-cases/get-signed-document-content.ts, apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-attachments-content.ts, apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-attachments.ts, apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-details.ts, apps/io-func-sign-user/src/infra/http/decoder/fiscal-code.ts, apps/io-func-sign-user/src/infra/http/decoder/signature-request.ts, apps/io-func-sign-user/src/infra/http/encoders/signature-request.ts, apps/io-func-sign-user/src/signature-request.ts, packages/io-sign/src/document-content.ts, packages/io-sign/src/infra/azure/storage/blob.ts, packages/io-sign/src/infra/azure/storage/document-content.ts, packages/io-sign/src/infra/http/response.ts, packages/io-sign/src/signature-request.ts, yarn.lock
This PR implements the 2 endpoints needed to use messages with attachments.
In particular, the following endpoints have been implemented:
- `/messages/{signatureRequestId}` which allows you to obtain the list of documents (attachments) associated with a signature request.
- `/messages/{signatureRequestId}/{documentId}` Which allows you to obtain the content of the single document in the `application/pdf` format
Tested locally with cloud resources
=> feat: [SFEQS-1404] Implement endpoints to use messages with attachments

.changeset/khaki-otters-mix.md, apps/io-func-sign-user/src/infra/http/encoders/signature-request.ts
Add `.pdf` extension to filename in third party message attachments.
=> fix: [SFEQS-1431] Add filename extension to ThirdPartyMessageApiModel

.changeset/six-dolphins-march.md, apps/io-func-sign-user/package.json, apps/io-func-sign-user/src/app/use-cases/__mocks__/qtsp.ts, apps/io-func-sign-user/src/app/use-cases/create-signature.ts, apps/io-func-sign-user/src/infra/azure/functions/create-signature.ts, apps/io-func-sign-user/src/infra/namirial/encoders/signature-request.ts, apps/io-func-sign-user/src/infra/namirial/signature-request.ts, apps/io-func-sign-user/src/qtsp.ts, yarn.lock
This PR modifies the mock signature sent to the QTSP as expected by Lollipop 🍭
- Added `signatureInput` parameter to QTSP API
- Added public key to `JWK` changeover
- Added calculation of signatureParams and related signatures
- Added `inResponseTo` field inside SAML with public key hash
This mock allows us to test the integration with the QTSP even without the presence of the signatures affixed by the app!
tested locally with cloud resources and QTSP UAT environment
=> feat(user): [SFEQS-1479] Lollipop integration mock   🍭

.changeset/gorgeous-tigers-refuse.md, .changeset/great-moons-perform.md, apps/io-func-sign-issuer/CreateIssuerByVatNumberView/function.json, apps/io-func-sign-issuer/src/__test__/signature-request-notification.spec.ts, apps/io-func-sign-issuer/src/__test__/signature-request.spec.ts, apps/io-func-sign-issuer/src/__test__/upload.spec.ts, apps/io-func-sign-issuer/src/app/main.ts, apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts, apps/io-func-sign-issuer/src/infra/azure/functions/create-issuers-by-vat-number-view.ts, packages/io-sign/src/issuer.ts
1. Add a new function, triggered by cosmos db, called `CreateIssuerByVatNumberView`
2. Add `vatNumber` property on `Issuer` entity
This function creates a "lookup" collection on CosmosDB that allows us to get issuers by their vat number instead of `(issuer.id, subscription.id)`
=> feat(issuer): [SFEQS-1505] Add CreateIssuerByVatNumberView function

.github/workflows/release.yaml
- release github action, clone step, fetch depth to 0
Due to actions/checkout#701 in order to also fetch tags, the parameter `fetch-depth` has to be set to zero.
Without fetching tags the automation wrongly tried to retag already existing branches.
=> fix(ci): Set fetch-depth in roder to include tags

packages/io-sign-issuer-sdk/package.json, packages/io-sign-issuer-sdk/src/signature-request.ts, yarn.lock
This PR applies some fixes to the SDK that is being developed by @filippo-tenaglia 
In particular:
- Adds better error handling
- Adds a patch on document upload and validation
Thanks to this SDK a very important BUG of `io-sign` has come out. In particular, it is not possible to upload all the files together (although they have different urls and the API allow it) and then validate them as there is no lock on the DB resources. What you have to do is wait for each single document to be validated before moving on to the next document.
I will do a more detailed description of this bug on confluence.
=> chore: Code refactor and patch document validation on issuer SDK

.changeset/violet-mangos-jog.md, apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts, apps/io-func-sign-issuer/src/infra/azure/cosmos/signature-request.ts, apps/io-func-sign-issuer/src/infra/http/handlers/__test__/create-signature-request.spec.ts, apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-requests-by-dossier.spec.ts, apps/io-func-sign-issuer/src/infra/http/handlers/__test__/get-signature-request.spec.ts, apps/io-func-sign-issuer/src/signature-request.ts
Fixes a bug that didn't allow documents to be uploaded at the same time due to a concurrency issue. 
- Added the function for patching a single document on the signatureRequest object present on cosmosDb
More detail [here](https://pagopa.atlassian.net/wiki/spaces/SFEQS/pages/713162998/IO-SIGN-RFC-BUG-0001+Bug+sul+processo+di+validazione+dei+documenti)
Tested locally
=> fix: [SFEQS-1660] Add `patchDocument` to signature request db model

.changeset/eight-terms-visit.md, packages/io-sign/src/infra/pdf.ts
1. now in `PdfDocumentMetadata` are included only `PDFSignature` fields
the issuers was unable to upload PDF documents that contains text fields
=> fix (issuer): [SFEQS-1708] Fix document validation on PDF with text fields

apps/io-sign-backoffice-ca/.env, apps/io-sign-backoffice-ca/.env.development, apps/io-sign-backoffice-ca/.gitignore, apps/io-sign-backoffice-ca/next.config.js, apps/io-sign-backoffice-ca/package.json, apps/io-sign-backoffice-ca/src/app/[locale]/[institution]/layout.tsx, apps/io-sign-backoffice-ca/src/app/[locale]/[institution]/page.tsx, apps/io-sign-backoffice-ca/src/app/[locale]/_components/Footer.tsx, apps/io-sign-backoffice-ca/src/app/[locale]/_components/HeaderWithAccountInfo.tsx, apps/io-sign-backoffice-ca/src/app/[locale]/layout.tsx, apps/io-sign-backoffice-ca/src/app/[locale]/page.tsx, apps/io-sign-backoffice-ca/src/app/auth/[id]/route.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/__test__/self-care.spec.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/__test__/session.spec.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/__test__/user.spec.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/self-care.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/session.ts, apps/io-sign-backoffice-ca/src/app/auth/_lib/user.ts, apps/io-sign-backoffice-ca/src/app/auth/logout/route.ts, apps/io-sign-backoffice-ca/src/components/mui/index.ts, apps/io-sign-backoffice-ca/src/config.ts, apps/io-sign-backoffice-ca/src/i18n.tsx, apps/io-sign-backoffice-ca/src/messages/it.json, apps/io-sign-backoffice-ca/src/middleware.ts, apps/io-sign-backoffice-ca/vitest.config.js, yarn.lock
1. Added `/auth/[id]` and `/auth/logout` routes to manage authentication. The first one verifies the id token passed by self care portal and creates a sealed session cookie (like [the ones in ruby on rails](https://guides.rubyonrails.org/security.html#session-storage) ) based on jwt, the second route destroys the cookie.
2. Improved translation, now they are totally server-side driven. No more `messages.json` in `bundle.js` and delays/FUOC while resolving the translations.
3. Improved the main header with documentation, support and logout button. Added the footer.
4. Added a proper home page!
5. Revamped the project structure, to use a more "idiomatic" style for Next.js and React standards.
With this changes we are now able to deploy safely this service in production :) 
The …
=> feat(backoffice): [SFEQS-1885] Implemented authentication from Self Care + minor improvements

.changeset/forty-ladybugs-obey.md, apps/io-func-sign-issuer/src/infra/back-office/issuer.ts, apps/io-func-sign-issuer/src/issuer.ts, apps/io-sign-backoffice-app/src/app/api/api-keys/[api-key]/route.ts, apps/io-sign-backoffice-app/src/lib/__test__/api-keys.spec.ts, apps/io-sign-backoffice-app/src/lib/api-keys/cosmos.ts, apps/io-sign-backoffice-app/src/lib/api-keys/index.ts, apps/io-sign-backoffice-app/src/lib/institutions/selfcare.ts, apps/io-sign-backoffice-app/src/lib/issuers/index.ts
1. Changed `ApiKey` decoder to reflect changes on backoffice side
2. Relax validation rules on `id`
3. Fix `getApiKey` query
`getIssuerBySubscriptionId`  no longer works due to some changes on the backoffice service, this PR fixes the bug.
=> fix(bo, issuer): [SFEQS-2004] Get Issuer data from Ocp-Apim-Subscription-Id

apps/io-func-sign-user/openapi.yaml, apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-details.ts, apps/io-func-sign-user/src/infra/http/handlers/__test__/get-signature-request.spec.ts, apps/io-func-sign-user/src/infra/http/handlers/get-signature-request.ts
1. renamed `x-firmaconio-environment` to `x-io-sign-environment` to make it uniform with the rest of the IO platform
2. removed this header from `/messages` endpoint
the `/message` endpoint should adhere to a "strict interface" that does not support additional headers
=> fix(user): [SFEQS-1889] change environment header

apps/io-sign-backoffice-app/src/lib/cosmos.ts
1. `getCosmosClient` now acts as a singleton
the actual implementation does not reuse the instantiated client, so maybe it's the cause of the memory leak in production
=> fix(bo): [SFEQS-2048] fix getCosmosClient

.changeset/modern-penguins-speak.md, packages/io-sign/src/infra/io-services/message.ts
`submitMessageForUser` now submits `ADVANCED` messages instead of `STANDARD` ones
From **Monday 18 December 2023**, to send messages with attachments, it's mandatory to set `feature_level_type` as `ADVANCED`. Reference https://github.com/pagopa/io-functions-services/pull/291
=> chore(io-services): [SFEQS-2077] Switch to ADVANCED messages

.changeset/ninety-needles-sleep.md, apps/io-func-sign-issuer/local.settings.json.example, apps/io-func-sign-issuer/src/app/main.ts, apps/io-func-sign-issuer/src/infra/azure/functions/mark-as-rejected.ts, apps/io-func-sign-issuer/src/infra/azure/functions/mark-as-signed.ts, apps/io-func-sign-issuer/src/infra/azure/functions/send-notification.ts, packages/io-sign/package.json, packages/io-sign/src/infra/io-services/config.ts, packages/io-sign/src/infra/io-services/message.ts, yarn.lock
1. Added `configuration_id` (populated by reading the environment) to the request body of `submitMessageforUserWithFiscalCodeInBody `
The `configuration_id` field will be soon mandatory for all `io-services` consumer
This change was tested manually (e2e)
=> chore(io-services): [SFEQS-2091] Set configurationId in submitMessage

.changeset/chilled-fishes-sip.md, apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts, packages/io-sign/src/institution.ts
The `billing` and `vatNumber` properties in the `contractSchema` and `onboardingSchema`  have become optional
In the message arriving on the `sc-contracts` queue, the `billing` property has become optional, as well as the `vatNumber` property in `billing`
=> fix: set vatNumber in sc-contracts as optional field
